# 1. Loading Dataset

In [9]:
import pandas as pd
import kagglehub
import os

In [10]:
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

In [11]:
# Download latest version
path = kagglehub.dataset_download("lakshmi25npathi/imdb-dataset-of-50k-movie-reviews")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'imdb-dataset-of-50k-movie-reviews' dataset.
Path to dataset files: /kaggle/input/imdb-dataset-of-50k-movie-reviews

In [12]:
df=pd.read_csv('/kaggle/input/imdb-dataset-of-50k-movie-reviews/IMDB Dataset.csv')

In [13]:
df.head()

df.isnull().sum()

df.shape

df.drop_duplicates(inplace=True)

In [14]:
df.shape

(49582, 2)

# 2 - PreProcessing Data

<h4> 2.1. Converting to Lowercase

In [15]:
df['review'] = df["review"].str.lower()

In [16]:
df["review"].sample(10)

34250    i really enjoyed this movie. the humor was a b...
30765    this movie could have had a lot of potential. ...
33978    how awful is it? let me count the ways: 1) it ...
44865    a few years ago, a friend got from one of his ...
41953    songwriter robert taylor (as terry) is "dizzy,...
4985     look at the all the positive user comments of ...
43935    much better than expected. good family flick -...
551      i was expecting a lot from mr.amitabh bachan's...
17347    i know nothing of the iliad so can not comment...
28584    the perfectly stupid weapon. i think the guys ...
Name: review, dtype: object

<h4> 2.2 Removing URLS

In [17]:
#making use of regular expression here

import re

def remove_urls(text):
   text =  re.sub(r"http\S+" , "", text)
   return text

df["review"] = df["review"].apply(remove_urls)

<h4> 2.3 Removing Punctuation

In [18]:
def remove_punctuation(text):
    text = re.sub(r"[^A-za-z0-9\s]", "", text)
    return text


df["review"] = df["review"].apply(remove_punctuation)

In [19]:
df.head()

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production br br the filmin...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically theres a family where a little boy j...  negative
4  petter matteis love in the time of money is a ...  positive

<h4> 2.4 Removing HTML tags

In [20]:
def remove_html_tags(text):
    text = re.sub(r"<.*>?", "", text)           
    return text

df["review"] = df["review"].apply(remove_html_tags)

<h4> 2.5 Removing the StopWord

In [21]:
import nltk

In [22]:
nltk.download("punkt")
nltk.download("punkt_tab")
nltk.download("stopwords")

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [23]:
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords           # we will get all English Words from here

In [24]:
#Simple Example for stopword

sample_text = "I like riding bike on seashore#!"
token_text = word_tokenize(sample_text)

print(token_text)

['I', 'like', 'riding', 'bike', 'on', 'seashore', '#', '!']

In [25]:

from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords    

    # we will get all English Words from here
def remove_stopword(text):
    tokens = word_tokenize(text)
    stop_words = stopwords.words("english")


    for word in tokens:
        if word in stop_words:
            text.replace(word,"")

    return text


df['review'] = df['review'].apply(remove_stopword)

In [26]:
df.head()

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production br br the filmin...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically theres a family where a little boy j...  negative
4  petter matteis love in the time of money is a ...  positive

<h4> 2.6 Stemming word

In [27]:
from nltk.stem import PorterStemmer

In [28]:
def stemming(text):
    ps = PorterStemmer()
    stemmed_words = []

    tokens = word_tokenize(text)

    for token in tokens:
        stemmed_token = ps.stem(token)
        stemmed_words.append(stemmed_token)


    return " ".join(stemmed_words)

df['review'] = df['review'].apply(stemming)

In [29]:
df.head()

                                              review sentiment
0  one of the other review ha mention that after ...  positive
1  a wonder littl product br br the film techniqu...  positive
2  i thought thi wa a wonder way to spend time on...  positive
3  basic there a famili where a littl boy jake th...  negative
4  petter mattei love in the time of money is a v...  positive

<h4> 2.7 Encoding

In [30]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['sentiment'] =  le.fit_transform(df["sentiment"])

In [31]:
y = df["sentiment"]

In [32]:
y

0        1
1        1
2        1
3        0
4        1
        ..
49995    1
49996    0
49997    0
49998    0
49999    0
Name: sentiment, Length: 49582, dtype: int64

<h4> 2.8 Vectorization

In [33]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [34]:
tf = TfidfVectorizer(max_features=5000)
X = tf.fit_transform(df["review"])

print(X)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 5870823 stored elements and shape (49582, 5000)>
  Coords	Values
  (0, 3122)	0.02032235608369572
  (0, 3097)	0.09542022747629417
  (0, 4440)	0.2090330132232405
  (0, 3151)	0.05716619914669184
  (0, 3689)	0.047949808899860516
  (0, 2024)	0.024836929580541244
  (0, 2808)	0.050935830362513514
  (0, 4438)	0.06274904433157914
  (0, 162)	0.03225992525225194
  (0, 4820)	0.07851528966051344
  (0, 2474)	0.048503669789957786
  (0, 3184)	0.4321643975842991
  (0, 1535)	0.1027404052594663
  (0, 4987)	0.05289330313334046
  (0, 443)	0.057113196906311316
  (0, 2178)	0.07161312142940703
  (0, 4455)	0.02444267451829711
  (0, 300)	0.041296249645157386
  (0, 3712)	0.08249918784461986
  (0, 323)	0.07507383896113437
  (0, 4460)	0.04274825380760872
  (0, 2385)	0.12958823617369689
  (0, 1583)	0.05594482912965905
  (0, 4864)	0.04993287193962988
  (0, 2052)	0.0411823818124307
  :	:
  (49581, 2284)	0.093699600713864
  (49581, 1655)	0.16514908162678008
  (49581, 2206)	0.0807042470626285
  (49581, 4603)	0.0912443357223629
  (49581, 776)	0.1060671377962548
  (49581, 3828)	0.09696047506820302
  (49581, 2522)	0.10984214286872186
  (49581, 4659)	0.09944328078326373
  (49581, 2584)	0.09254294341530585
  (49581, 2352)	0.139746257364197
  (49581, 378)	0.11062245667191671
  (49581, 2060)	0.12366188945068267
  (49581, 3640)	0.10501008856241198
  (49581, 2265)	0.16039136997872677
  (49581, 317)	0.10474091502651066
  (49581, 4584)	0.1548902935644654
  (49581, 2510)	0.17799838402868834
  (49581, 4160)	0.19519235561454026
  (49581, 1088)	0.15522786068323782
  (49581, 682)	0.14320422584940157
  (49581, 3023)	0.15987610785210737
  (49581, 2941)	0.16868965639367686
  (49581, 778)	0.125412664165706
  (49581, 1956)	0.1531881175323897
  (49581, 3641)	0.14696162670390306