# 1. Loading Dataset

In [1]:
import pandas as pd
import kagglehub
import os

In [2]:
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

/kaggle/input/imdb-dataset-of-50k-movie-reviews/IMDB Dataset.csv

In [3]:
# Download latest version
path = kagglehub.dataset_download("lakshmi25npathi/imdb-dataset-of-50k-movie-reviews")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'imdb-dataset-of-50k-movie-reviews' dataset.
Path to dataset files: /kaggle/input/imdb-dataset-of-50k-movie-reviews

In [4]:
df=pd.read_csv('/kaggle/input/imdb-dataset-of-50k-movie-reviews/IMDB Dataset.csv')

In [5]:
df.head()

df.isnull().sum()

df.shape

df.drop_duplicates(inplace=True)

In [6]:
df.shape

(49582, 2)

# 2 - PreProcessing Data

<h4> 2.1. Converting to Lowercase

In [7]:
df['review'] = df["review"].str.lower()

In [8]:
df["review"].sample(10)

10041    i wasn't expecting much from this tale of a ki...
16828    this series premiered on the cable tv station ...
32328    it's been over 30 years now but i still rememb...
43992    i've barely just made it through one episode (...
35887    i'm dumbfounded. yes that's right. i'm really ...
22400    "at the earth's core" was on television yester...
41958    gruveyman2 (comment below)you are a complete i...
26770    made me think about it for days after seeing i...
45657    i thought "the river of souls" was a very good...
46239    possible spoilers as peter jackson has so bril...
Name: review, dtype: object

<h4> 2.2 Removing URLS

In [9]:
#making use of regular expression here

import re

def remove_urls(text):
   text =  re.sub(r"http\S+" , "", text)
   return text

df["review"] = df["review"].apply(remove_urls)

<h4> 2.3 Removing Punctuation

In [10]:
def remove_punctuation(text):
    text = re.sub(r"[^A-za-z0-9\s]", "", text)
    return text


df["review"] = df["review"].apply(remove_punctuation)

In [11]:
df.head()

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production br br the filmin...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically theres a family where a little boy j...  negative
4  petter matteis love in the time of money is a ...  positive

<h4> 2.4 Removing HTML tags

In [12]:
def remove_html_tags(text):
    text = re.sub(r"<.*>?", "", text)           
    return text

df["review"] = df["review"].apply(remove_html_tags)

<h4> 2.5 Removing the StopWord

In [13]:
import nltk

In [14]:
nltk.download("punkt")
nltk.download("punkt_tab")
nltk.download("stopwords")

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [15]:
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords           # we will get all English Words from here

In [16]:
#Simple Example for stopword

sample_text = "I like riding bike on seashore#!"
token_text = word_tokenize(sample_text)

print(token_text)

['I', 'like', 'riding', 'bike', 'on', 'seashore', '#', '!']

In [17]:

from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords    

    # we will get all English Words from here
def remove_stopword(text):
    tokens = word_tokenize(text)
    stop_words = stopwords.words("english")


    for word in tokens:
        if word in stop_words:
            text.replace(word,"")

    return text


df['review'] = df['review'].apply(remove_stopword)

In [18]:
df.head()

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production br br the filmin...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically theres a family where a little boy j...  negative
4  petter matteis love in the time of money is a ...  positive

<h4> 2.6 Stemming word

In [19]:
from nltk.stem import PorterStemmer

In [20]:
def stemming(text):
    ps = PorterStemmer()
    stemmed_words = []

    tokens = word_tokenize(text)

    for token in tokens:
        stemmed_token = ps.stem(token)
        stemmed_words.append(stemmed_token)


    return " ".join(stemmed_words)

df['review'] = df['review'].apply(stemming)

In [21]:
df.head()

                                              review sentiment
0  one of the other review ha mention that after ...  positive
1  a wonder littl product br br the film techniqu...  positive
2  i thought thi wa a wonder way to spend time on...  positive
3  basic there a famili where a littl boy jake th...  negative
4  petter mattei love in the time of money is a v...  positive

<h4> 2.7 Encoding

In [22]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['sentiment'] =  le.fit_transform(df["sentiment"])

In [23]:
y = df["sentiment"]

In [24]:
y

0        1
1        1
2        1
3        0
4        1
        ..
49995    1
49996    0
49997    0
49998    0
49999    0
Name: sentiment, Length: 49582, dtype: int64

<h4> 2.8 Vectorization

In [25]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [26]:
tf = TfidfVectorizer(max_features=5000)
X = tf.fit_transform(df["review"])

print("Vectorized Data :",X)

Vectorized Data : <Compressed Sparse Row sparse matrix of dtype 'float64'
	with 5870823 stored elements and shape (49582, 5000)>
  Coords	Values
  (0, 3122)	0.02032235608369572
  (0, 3097)	0.09542022747629417
  (0, 4440)	0.2090330132232405
  (0, 3151)	0.05716619914669184
  (0, 3689)	0.047949808899860516
  (0, 2024)	0.024836929580541244
  (0, 2808)	0.050935830362513514
  (0, 4438)	0.06274904433157914
  (0, 162)	0.03225992525225194
  (0, 4820)	0.07851528966051344
  (0, 2474)	0.048503669789957786
  (0, 3184)	0.4321643975842991
  (0, 1535)	0.1027404052594663
  (0, 4987)	0.05289330313334046
  (0, 443)	0.057113196906311316
  (0, 2178)	0.07161312142940703
  (0, 4455)	0.02444267451829711
  (0, 300)	0.041296249645157386
  (0, 3712)	0.08249918784461986
  (0, 323)	0.07507383896113437
  (0, 4460)	0.04274825380760872
  (0, 2385)	0.12958823617369689
  (0, 1583)	0.05594482912965905
  (0, 4864)	0.04993287193962988
  (0, 2052)	0.0411823818124307
  :	:
  (49581, 2284)	0.093699600713864
  (49581, 1655)	0.16514908162678008
  (49581, 2206)	0.0807042470626285
  (49581, 4603)	0.0912443357223629
  (49581, 776)	0.1060671377962548
  (49581, 3828)	0.09696047506820302
  (49581, 2522)	0.10984214286872186
  (49581, 4659)	0.09944328078326373
  (49581, 2584)	0.09254294341530585
  (49581, 2352)	0.139746257364197
  (49581, 378)	0.11062245667191671
  (49581, 2060)	0.12366188945068267
  (49581, 3640)	0.10501008856241198
  (49581, 2265)	0.16039136997872677
  (49581, 317)	0.10474091502651066
  (49581, 4584)	0.1548902935644654
  (49581, 2510)	0.17799838402868834
  (49581, 4160)	0.19519235561454026
  (49581, 1088)	0.15522786068323782
  (49581, 682)	0.14320422584940157
  (49581, 3023)	0.15987610785210737
  (49581, 2941)	0.16868965639367686
  (49581, 778)	0.125412664165706
  (49581, 1956)	0.1531881175323897
  (49581, 3641)	0.14696162670390306

<h3> 3. TensorDataset & DataLoader

In [27]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [28]:
X_train.shape

(39665, 5000)

In [29]:
X_test.shape

(9917, 5000)

In [30]:
X_train = X_train.toarray()
X_test = X_test.toarray()

In [31]:
import torch
from torch.utils.data import TensorDataset, DataLoader

train_set = TensorDataset(
    torch.from_numpy(X_train).float(),
    torch.from_numpy(y_train.values).float()
)

test_set = TensorDataset(
    torch.from_numpy(X_test).float(),
    torch.from_numpy(y_test.values).float()
)

In [32]:
train_loader = DataLoader(train_set, batch_size=64, shuffle=True)
test_loader = DataLoader(test_set, batch_size=64, shuffle=True)